version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       nodejs: 10
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - echo Installing yarn ..
      - npm i -g yarn
      - echo "Yarn Installing completed.."
      - echo "Yarn Installing node dependencies.."
      - yarn
      - echo "node dependencies are completed.."
      - yarn start
      - echo "build - Successfull... :)"
      - command
  post_build:
    commands:
        - echo "Post build - Successfull... :)"
        - command
  #reports:
    #enter-report-name-here:
      #files:
        # - location
        # - location
      #base-directory: location
      #discard-paths: yes
      #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - node_modules
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths